### ISSUE TITLE
Uncaught TypeError: Invalid Point: ((1, 0), 0)

### ISSUE THREAD

**Issue by vhdedic** [FleaRex/print-that#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [print-that](https://github.com/FleaRex/print-that) package 0.1.0

### Stack Trace

Uncaught TypeError: Invalid Point: ((1, 0), 0)

```
At /snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11

TypeError: Invalid Point: ((1, 0), 0)
    at Function.Point.assertValid (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:14:49613)
    at TextBuffer.clipPosition (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:496718)
    at MarkerLayer.setMarkerRange (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:14:81794)
    at Marker.update (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:14:72217)
    at Marker.setHeadPosition (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:14:68776)
    at DisplayMarker.setHeadBufferPosition (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:14:2852319)
    at changePosition (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:522686)
    at Cursor.changePosition (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:531073)
    at Cursor.setBufferPosition (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:522652)
    at moveCursors.o (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:29229)
    at Array.forEach (<anonymous>)
    at transact (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:33144)
    at TextBuffer.transact (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:492395)
    at TextEditor.transact (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorBufferPosition (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:29212)
    at Object.getWholeLineRange (/packages/print-that/lib/print-that.js:66:12)
    at Object.reselectRow (/packages/print-that/lib/print-that.js:51:17)
    at Object.addPrintForRange (/packages/print-that/lib/print-that.js:44:20)
    at Object.addPrintStatements (/packages/print-that/lib/print-that.js:38:12)
    at Object.printSelected (/packages/print-that/lib/print-that.js:27:12)
    at HTMLElement.printThatPrintSelected (/packages/print-that/lib/print-that.js:16:46)
    at CommandRegistry.handleCommandEvent (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:349392)
    at CommandRegistry.dispatch (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:11:347867)
    at AtomEnvironment.dispatchApplicationMenuCommand (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:1:718771)
    at EventEmitter.t (/snap/atom/242/usr/share/atom/resources/app/static/<embedded>:1:726694)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
  2x -0:29.7.0 print-that:printSelected (input.hidden-input)
```

### Non-Core Packages

```
language-todo-more-words 2.7.0 
print-that 0.1.0 
sort-selected-elements 0.1.0 
```

**Comment by FleaRex** [comment]
Hi! Have you got any more information for reproducing?

**Comment by vhdedic** [comment]
Hi! I have no more information because I uninstalled this plugin.

**Comment by FleaRex** [comment]
Ok, no worries. I'll keep it in mind in case it comes up again, but as I don't think I'll be able to solve this issue, I'm going to close it. Thanks for trying the my plugin!
